Repository Alexiatech/Tech-D-groepsopdracht, pull requests merged in 2023-04, with the labels that each got.

#35 registreren aan gepast
  routes/alexiaroutes.js
  views/register.ejs
Labels: enhancement

#42 Disabled buttons that dont do anything and style
  routes/youriroutes.js
  static/styles/movieMatcher.css
  views/movieMatcherGenre.ejs
  views/movieMatcherLanguage.ejs
Labels: Styling

#47 Routes gewijzigd en error opgelost in likedmovies
  routes/larsroutes.js
  routes/youriroutes.js
  views/likedMovies.ejs
  views/movieMatcherResult.ejs
Labels: Small fixes

#48 HTTP Compression + lazyloading init
  package-lock.json
  package.json
  server.js
  static/scripts/lazysizes.js
  views/editProfile.ejs
  views/head-partial.ejs
  views/home.ejs
  views/likedMovies.ejs
  views/menu-partial.ejs
  views/movieMatcherDecade.ejs
  views/movieMatcherLanguage.ejs
  views/movieMatcherResult.ejs
  views/moviePage.ejs
  views/register.ejs
  views/signup.ejs
Labels: enhancement
